### ISSUE TITLE
백엔드 작업

### ISSUE THREAD

**Issue by 1006lem** [boanlab/kuri#4]
## Task List

- [ ] 그래프 간접 연결될 수 있는 리스트에 대해, 모든 network policy 검증하여 <br> **network policy에 위배되는 간접 연결 pod** 탐지  코드 작성
- [ ] REST API 구현
- [ ] 배포 진행 (java project -> docker file)
- [ ] 프론트엔드로 보낼 **데이터  조율** (변경 여지 있음)
- [ ] test case 생성
